// This file is automatically generated by Firebase Studio.
// Do not edit this file manually, as your changes will be overwritten.

export const firebaseConfig = {
  apiKey: "AIzaSyDuw4d27imNdJZXJ_RbokdfmJaA6KejwpE",
  authDomain: "thutodatabase.firebaseapp.com",
  projectId: "thutodatabase",
  storageBucket: "thutodatabase.firebasestorage.app",
  messagingSenderId: "10829041335",
  appId: "1:10829041335:web:9b89e899c256131e744732"
};
